import copy
import numpy as np
from langchain_core.documents import Document

# Modern Text Splitters Package
from langchain_text_splitters import CharacterTextSplitter

# Document Loaders (Still in community for now, but good practice to keep track)
from langchain_community.document_loaders import PyPDFLoader, Docx2txtLoader

# Dedicated Ollama Package
from langchain_ollama import OllamaEmbeddings

# NEW: Dedicated Chroma Partner Package
from langchain_chroma import Chroma

# 1. Load the document
loader = Docx2txtLoader("Introduction_to_Data_and_Data_Science.docx")
pages = loader.load()

# Initialize embeddings
embeddings = OllamaEmbeddings(model="nomic-embed-text")

# Clean text whitespace
for i in range(len(pages)):
    pages[i].page_content = " ".join(pages[i].page_content.split())

# 2. Split documents
character_splitter = CharacterTextSplitter(separator=".", chunk_size=1000, chunk_overlap=200)
pages_char_split = character_splitter.split_documents(pages)

print(f"Total Chunks: {len(pages_char_split)}")

# 3. Manually attach embeddings to metadata for analysis
for i in pages_char_split:
    i.metadata["embeddings"] = embeddings.embed_query(i.page_content)

print("\n--- Testing Document 0 Matrix Math ---")
# Vector Math Debugging
print(f"Embedding length: {len(pages_char_split[0].metadata['embeddings'])}")
print(f"Dot product (0 vs 1): {np.dot(pages_char_split[0].metadata['embeddings'], pages_char_split[1].metadata['embeddings'])}")
print(f"Norm of Doc 0: {np.linalg.norm(pages_char_split[0].metadata['embeddings'])}")

# 4. Initialize Vector Store (Using the new langchain_chroma import)
# Note: Added collection_name explicitly as it's highly recommended in newer versions
vector_store = Chroma.from_documents(
    documents=pages_char_split,
    embedding=embeddings,
    persist_directory="./index",
    collection_name="data_science_docs" 
)

# 5. Reloading the Vector Store from directory
vector_store_from_directory = Chroma(
    persist_directory="./index",
    embedding_function=embeddings,
    collection_name="data_science_docs"
)

# 6. Adding a new item dynamically
added_document = Document(
    page_content='Analysis vs Analytics Alright! So… Let’s discuss the not-so-obvious differences between the terms analysis and analytics...', 
    metadata={'source': 'Introduction_to_Data_and_Data_Science.docx'}
)

# add_documents returns a list of unique IDs generated by Chroma
inserted_ids = vector_store.add_documents([added_document])
print(f"\nInserted Document IDs: {inserted_ids}")

# 7. Similarity Search
results = vector_store.similarity_search("What is analytics", k=1)
print(f"\nTop Search Result: {results[0].page_content}")

# 8. Deleting an item
# Passing the dynamic ID we just got back from add_documents to ensure it exists
if inserted_ids:
    vector_store.delete(ids=[inserted_ids[0]])
    print(f"\nDeleted document with ID: {inserted_ids[0]}")